:job_id:01000000
:actor_name:WorkerGroupRegisterCenter
*** SIGSEGV received at time=1746377546 on cpu 4 ***
PC: @     0x76ca81eb78fe  (unknown)  ray::gcs::TaskInfoAccessor::AsyncAddTaskEventData()
    @     0x76ca83445330       3808  (unknown)
    @     0x76ca81d98ab5       1392  ray::core::worker::TaskEventBufferImpl::FlushEvents()
    @     0x76ca81d2182c       1488  ray::core::CoreWorker::Disconnect()
    @     0x76ca81d21bdd       1152  ray::core::CoreWorker::ForceExit()
    @     0x76ca81d22447         64  std::_Function_handler<>::_M_invoke()
    @     0x76ca820a6d08       1168  EventTracker::RecordExecution()
    @     0x76ca8208b13e         48  std::_Function_handler<>::_M_invoke()
    @     0x76ca8208b5b6        112  boost::asio::detail::completion_handler<>::do_complete()
    @     0x76ca82751a5b        128  boost::asio::detail::scheduler::do_run_one()
    @     0x76ca827533d9        288  boost::asio::detail::scheduler::run()
    @     0x76ca82753ae2         96  boost::asio::io_context::run()
    @     0x76ca81c7a1f1       1280  ray::core::CoreWorker::RunIOService()
    @     0x76ca82198620         64  thread_proxy
    @     0x76ca8349caa4        176  (unknown)
    @     0x76ca83529c3c  (unknown)  (unknown)
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484: *** SIGSEGV received at time=1746377546 on cpu 4 ***
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484: PC: @     0x76ca81eb78fe  (unknown)  ray::gcs::TaskInfoAccessor::AsyncAddTaskEventData()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca83445330       3808  (unknown)
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca81d98ab5       1392  ray::core::worker::TaskEventBufferImpl::FlushEvents()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca81d2182c       1488  ray::core::CoreWorker::Disconnect()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca81d21bdd       1152  ray::core::CoreWorker::ForceExit()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca81d22447         64  std::_Function_handler<>::_M_invoke()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca820a6d08       1168  EventTracker::RecordExecution()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca8208b13e         48  std::_Function_handler<>::_M_invoke()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca8208b5b6        112  boost::asio::detail::completion_handler<>::do_complete()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca82751a5b        128  boost::asio::detail::scheduler::do_run_one()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca827533d9        288  boost::asio::detail::scheduler::run()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca82753ae2         96  boost::asio::io_context::run()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca81c7a1f1       1280  ray::core::CoreWorker::RunIOService()
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca82198620         64  thread_proxy
[2025-05-04 18:52:26,441 E 1846844 1847002] logging.cc:484:     @     0x76ca8349caa4        176  (unknown)
[2025-05-04 18:52:26,442 E 1846844 1847002] logging.cc:484:     @     0x76ca83529c3c  (unknown)  (unknown)
Fatal Python error: Segmentation fault


Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, uvloop.loop, ray._raylet, numpy._core._multiarray_umath, numpy.linalg._umath_linalg, pyarrow.lib, pyarrow._json (total: 15)
